modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPLv3"

[[mods]]
modId = "sspb"
version = "${version}"
displayName = "Rubidium Shadowy Path Blocks"
displayURL="https://github.com/TexTrueStudio/SSPB-Forge"
logoFile="assets/sspb/icon.png"
credits="Rynnavinx"
authors="TexTrue, TexTrueStudio"
description = '''
RSPB reintroduces vanilla-like smooth lighting to non-full blocks (e.g. dirt paths and how they have dark shading when directly next to a full block) when using Rubidium.
'''

[[dependencies.sspb]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sspb]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"